### ISSUE TITLE
Enhance the readme[dot]md file

### ISSUE THREAD

**Issue by cosmicray001** [anirudhbagri/Tic-Tac-Toe#1]
Enhance the readme[dot]md file so that people can understand and play the game.

**Comment by cosmicray001** [comment]
@anirudhbagri , I would like to work on the readme[dot]me file. Please assign me this issue.

**Comment by cosmicray001** [comment]
@anirudhbagri , hey, I've worked on this issue. Could you please review?

**Comment by anirudhbagri** [comment]
Thanks!
Repo looks amazing now :)
