### ISSUE TITLE
add gitignore file

### ISSUE THREAD

**Issue by cosmicray001** [anirudhbagri/Tic-Tac-Toe#5]
A gitignore file is a text file placed in your git repository that tells git not to track certain files and folders that you don't want being uploaded to your master repository. [More...](https://www.cloudsavvyit.com/12905/what-is-a-gitignore-file-and-how-do-you-configure-it/#:~:text=3%20min%20read-,A%20.,setting%20up%20a%20new%20repo.)

**Comment by cosmicray001** [comment]
@anirudhbagri , Could you please assign this to me? Thank you!

**Comment by anirudhbagri** [comment]
I don't see a need to add gitignore file to this project. Could you give me a reason why we need this?

**Comment by cosmicray001** [comment]
@anirudhbagri , After the code compilation, some files get created(binary, executable, etc). Moreover, depending on the IDE, a repo can be created as well. That is why it is good practice to add a gitignore file.
In my case, I had to remove these two files.
![image](https://user-images.githubusercontent.com/32748530/136711597-c5d08109-5d23-445c-b954-098efda50946.png)
Thank you.
